[WIP] feat: Portfolio API
wafflestudio/wacruit-server pull request #13
Opened 2023-07-20 12:35 UTC by fivessun5

2023-07-21 13:36 UTC, minkyu97 requested changes
아래에서 언급한 것 이외에,
* `모듈.클래스` 와 같은 코드를 많이 작성하셨는데요, 그게 더 편할 수는 있는데... 무엇이 더 나은 방법이냐를 논하자는 건 아니고 개인적으로 다른 코드와의 통일성을 위해 그냥 `from ~~.모듈 import 클래스` 로 하는 게 좋겠습니다.
* pre-commit 을 설치하신 거 맞나요?? isort가 제대로 적용이 안 되어있는 것 같아서요. 만약 안 되어있다면 pre-commit 설치하고 지금까지 변경된 모든 파일에 적용해주세요.

2023-07-21 13:36 UTC, minkyu97 commented on wacruit/src/apps/portfolio/aws/config.py
> +REGION = "ap-northeast-2"
이거 통일성 있게 `.env` 로 통일하는 게 좋겠습니다.

2023-07-21 13:36 UTC, minkyu97 commented on wacruit/src/apps/portfolio/aws/s3/method.py
> +    DELETE = "delete_object"
apps.common 하위에 enum들 관리하는 공통 모듈 있습니다. 거기에서 함께 관리하는 게 좋겠습니다.

2023-07-21 13:36 UTC, minkyu97 commented on wacruit/src/apps/portfolio/exceptions.py
> +class NumPortfolioLimitException(HTTPException):
`WacruitException` 사용해주세요. swagger 에 적용하기 편하기 하기 위함입니다.

2023-07-21 13:36 UTC, minkyu97 commented on wacruit/src/apps/portfolio/views.py
> +@v1_router.get("/", response_model=list[schemas.PortfolioNameResponse])
앞서 말한 `WacruitException` 적용 후 `responses`에 추가해주세요.

2023-07-21 13:36 UTC, minkyu97 commented on wacruit/src/apps/portfolio/schemas.py
> +from wacruit.src.apps.judge.schemas import JudgeSubmissionStatusModel
안 쓰는 import 문들 제거해주세요.

2023-07-21 13:36 UTC, minkyu97 commented on wacruit/src/apps/portfolio/services.py
> +import time
이것도 안 쓰는 거면 제거해주세용

2023-07-21 13:36 UTC, minkyu97 commented on wacruit/src/apps/portfolio/aws/s3/utils.py
> +    return [content["Key"] for content in resp["Contents"]]
content에 "Key" 라는 키가 없을 경우 None을 내뱉는 구조인가요?
response type이 `list[str | None]` 이길래 여쭤봅니다.

2023-07-21 13:36 UTC, minkyu97 commented on wacruit/src/apps/portfolio/views.py
> +):
가급적이면 views 에서는 response 타입 적어주세요.
response_model 대신 response 타입으로 validation 및 self-documentation 하는 게 더 가독성이 좋기도 하고 지금까지 다른 코드들도 그렇게 작성되어서요.

2023-07-21 13:37 UTC, minkyu97 commented
파일 개수가 아니라 크기를 제한하는 로직은 없는 거죠??

2023-07-21 13:59 UTC, shp7724 commented on wacruit/src/apps/portfolio/aws/s3/client.py
`/aws/s3/*`가 `portfolio` 앱 안에 있는게 살짝 갸우뚱하긴 하네요
밖으로 빼는건 어떤가요?

2023-07-21 13:59 UTC, shp7724 commented on wacruit/src/apps/portfolio/aws/s3/client.py
> +        return self._client
단순 궁금증.. 이거랑 `self.client`로 선언하는건 어떻게 다른가요?

2023-07-21 13:59 UTC, shp7724 commented on wacruit/src/apps/portfolio/services.py
> +        return [obj[len(str(user_id)) + 1:] for obj in objects]
`.split` 사용해서 좀더 깔끔하게 표현할 수 있을것같아요

2023-07-22 03:05 UTC, fivessun5 commented on wacruit/src/apps/portfolio/aws/s3/method.py
> +    DELETE = "delete_object"
common 에서 관리할만큼 다들 사용될 Enum 일까요?

2023-07-22 03:05 UTC, fivessun5 commented on wacruit/src/apps/portfolio/exceptions.py
> +class NumPortfolioLimitException(HTTPException):
넵 적용했습니다

2023-07-22 03:06 UTC, fivessun5 commented on wacruit/src/apps/portfolio/services.py
> +import time
넵

2023-07-22 03:07 UTC, fivessun5 commented on wacruit/src/apps/portfolio/aws/s3/client.py
이게 고민이긴한데, 위 Enum 처럼 확장성 있게 s3 util 들을 개발한게 아니라 portfolio API 에서 사용하기 좋게 만들어놔서요.
다른 곳에서 사용처가 있을지 의문입니다

2023-07-22 03:09 UTC, fivessun5 commented on wacruit/src/apps/portfolio/aws/s3/client.py
> +        return self._client
그냥 __init__ 에서 self.client 를 선언하면, 이후 객체의 외부 사용처에서 variable 을 맘대로 접근 밑 변경이 가능하지만, property 로 선언하면 변경이 불가능해져서 위처럼 정의했습니다. self._client 를 수정하면 되긴하지만,  해당 변수는 private 으로 선언해 외부에서 호출하지 말라고 표시해두었습니다

2023-07-22 03:48 UTC, shp7724 commented on wacruit/src/apps/portfolio/aws/s3/client.py
> +        return self._client
아 getter로만 하고 싶어서 이렇게 하신거군요. 이해했습니다.

2023-07-22 05:01 UTC, minkyu97 commented on wacruit/src/apps/portfolio/aws/s3/method.py
> +    DELETE = "delete_object"
ㅇㅎ 근데 사실 저기있는 Enum들도 여러 곳에서 쓰이는 게 아닌 데도 그냥 모아놓고 쓰는 거라.. 정책을 정하기 나름이긴한데 그렇게 생각하시면 꼭 옮길 필요는 없을 것 같습니다.

2023-07-22 13:11 UTC, fivessun5 commented on wacruit/src/apps/portfolio/aws/config.py
> +REGION = "ap-northeast-2"
추가했습니다만, 실제 배포시에는 EKS 에 주입해야할 듯 한데, 어떻게 하는게 좋을까요?? 인프라 쪽에 후속 PR 을 올리면 될까요?

2023-07-22 13:11 UTC, fivessun5 commented on wacruit/src/apps/portfolio/aws/config.py
> +REGION = "ap-northeast-2"
Done

2023-07-22 13:11 UTC, fivessun5 commented on wacruit/src/apps/portfolio/schemas.py
> +from wacruit.src.apps.judge.schemas import JudgeSubmissionStatusModel
Done

2023-07-22 13:12 UTC, fivessun5 commented on wacruit/src/apps/portfolio/views.py
> +):
넵~

2023-07-22 13:12 UTC, fivessun5 commented on wacruit/src/apps/portfolio/services.py
> +        return [obj[len(str(user_id)) + 1:] for obj in objects]
흠 반영은 해두었는데, 둘다 막 깔끔하진 않네요 ㅋㅋ 그래도 반영 완료

2023-07-22 13:19 UTC, fivessun5 commented on wacruit/src/apps/portfolio/views.py
> +@v1_router.get("/", response_model=list[schemas.PortfolioNameResponse])
반영했습니다

2023-07-22 13:20 UTC, fivessun5 commented on .env.test
> +PORTFOLIO_BUCKET_NAME=wacruit-portfolio
이건...현재 방법이 없어서 넣어두었는데 포폴 API 테스트코드를 어떤 식으로 작성해야할지 고민이라 Empty String 으로 주었습니다

2023-07-22 13:25 UTC, minkyu97 commented on wacruit/src/apps/portfolio/aws/config.py
> +REGION = "ap-northeast-2"
음 아녀 이거 https://github.com/wafflestudio/wacruit-server/blob/develop/wacruit/src/database/config.py 여기 참고해서 환경변수 말고 `pydantic.BaseSettings` 쓰시고, 배포 환경에서는 aws secret manager로 들고오도록 변경해주세요. 시크릿매니저에 추가는 @shp7724 가 해줄겁니다.

2023-07-22 13:46 UTC, fivessun5 commented on wacruit/src/apps/portfolio/aws/config.py
> +REGION = "ap-northeast-2"
저 정보가 SSM 통해서 들고올만큼 보안이 필요한 정보인가요?

2023-07-22 13:46 UTC, fivessun5 commented on wacruit/src/apps/portfolio/aws/s3/utils.py
> +    return [content["Key"] for content in resp["Contents"]]
확인해보니 Contents 라는 키의 유무로 결정되서 관련 처리 추가했어요..!

2023-07-22 14:17 UTC, minkyu97 commented on wacruit/src/apps/portfolio/aws/s3/utils.py
> +    return [content["Key"] for content in resp["Contents"]]
잘 이해가 안 되는데... Contents 라는 키가 없으면
`resp["Contents"]` 가 `None`이 되는 건가요? 아니면 `[]`?
`list[None]` 가능한 경우이려면 `content["Key"]`가 `None` 을 반환하는 게 아니면 상상이 잘 안 가서요.

2023-07-22 14:18 UTC, minkyu97 commented on wacruit/src/apps/portfolio/aws/config.py
> +REGION = "ap-northeast-2"
제가 코드를 짠 게 아니라 보안이 필요한지는 잘 모르겠습니다만... 시크릿 매니저를 사용하지 않더라도 통일성 있게 `pydantic.BaseSettings` 를 쓰지 않을 이유가 없어보입니다.

2023-07-22 14:20 UTC, fivessun5 commented on wacruit/src/apps/portfolio/aws/config.py
> +REGION = "ap-northeast-2"
bucket 이름과 region 이라 저 환경변수 이전 세팅처럼 그냥 코드에 두어도 될것 같아서 말씀드린거였어요.

2023-07-22 14:20 UTC, minkyu97 commented on wacruit/src/apps/portfolio/aws/config.py
> +REGION = "ap-northeast-2"
dev, prod, local, test 상황에서 모두 동일한 값인가요?

2023-07-23 12:55 UTC, fivessun5 commented on wacruit/src/apps/portfolio/aws/config.py
> +REGION = "ap-northeast-2"
흠... prod/dev 만큼은 분리해야할 것 같네요. 하지만 SSM 을 쓸 필요는 여전히 없어보이고, EKS pod 에 환경변수로 주입만 해주면 될것 같습니다. BaseSetting 을 이용해서 구현은 해두었어요

2023-07-23 13:54 UTC, fivessun5 reviewed
포폴 파일 뿐 아니라, url 을 등록할 수도 있어야한다고 하셔서 관련 API 를 추가했습니다.
파일 관련 API 는 DB 에 접근하지 않고, 반대로 URL 관련 API 에서는 S3 에 접근할 일이 없어서, 
두 API 의 폴더를 분리해서 구현했습니다.

조금 급하게 짜서 테스트 코드는 화요일 까진 추가로 올리겠습니다.
마이그레이션 파일도 일단 제외했습니다.

2023-07-23 13:54 UTC, fivessun5 commented on wacruit/src/apps/portfolio/file/aws/s3/utils.py
> +    if "Contents" not in resp.keys():
Contents 키가 없으면, 해당 prefix 를 가진 object 가 없다는 의미여서 이처럼 예외처리했습니다

2023-07-23 13:55 UTC, fivessun5 commented on wacruit/src/apps/portfolio/aws/s3/utils.py
> +    return [content["Key"] for content in resp["Contents"]]
https://github.com/wafflestudio/wacruit-server/pull/13#discussion_r1271452379

2023-07-23 14:08 UTC, fivessun5 commented on wacruit/src/apps/portfolio/url/models.py
> +    url: Mapped[str255] = mapped_column(nullable=False)
url길이가 감이 안와서... 모자를까요?

2023-07-23 14:19 UTC, minkyu97 reviewed
수고하셨슴다
테스트만 추가하고 머지하면 될 것 같네요

2023-07-23 14:54 UTC, minkyu97 commented on wacruit/src/apps/portfolio/url/models.py
> +    # user: Mapped["User"] = relationship(back_populates="portfolio_upload")
안 쓰는 거면 없어도 될 것 같아요. 근데 저도 sqlalchemy에 대해 모르는 게 많아서...

2023-07-23 14:56 UTC, minkyu97 commented on wacruit/src/apps/portfolio/file/aws/s3/utils.py
> +    if "Contents" not in resp.keys():
아하 넵 이건 이해했는데 제가 궁금했던 건... 여기서 return 해주는 게 빈 리스트 or 문자열이 들어간 리스트 둘 중 하나 아닌가요?? 그렇다면 반환타입이 `list[str]` 이 맞는 것 같아서 계속 질문드린거였어요.
반환타입이 `list[str | None]` 이라는 건 예를 들어 `["key1", "key2", None, "key4"]` 이런 식으로 반환할 수도 있다는 뜻이라서요.

2023-07-23 14:58 UTC, minkyu97 commented on wacruit/src/apps/portfolio/url/models.py
> +    url: Mapped[str255] = mapped_column(nullable=False)
방금 구글 드라이브 아무거나 파일 링크 가져와봤는데 약 100자 정도 되네요
그냥 이대로 하고 클라에다가 255자 제한이라고 명시해두면 될 것 같아요!

2023-07-24 23:53 UTC, fivessun5 commented on wacruit/src/apps/portfolio/file/aws/s3/utils.py
> +    if "Contents" not in resp.keys():
아 empty list 인 경우에 list[str | None] 이 아니라 list [str] 이 맞는 annotation 인가 보군요?? 알려주셔서 감사합니다 몰랐네요 ㅋㅋ
반영했습니다

2023-07-24 23:56 UTC, fivessun5 commented on wacruit/src/apps/portfolio/url/models.py
> +    )
수정은했는데, 혹시 이거 쓰면 마이그레이션 파일에서도 수정이 필요한가요?

2023-07-24 23:56 UTC, fivessun5 commented
테스트 코드 추가 및 리뷰 반영 완료했어요~

2023-07-25 10:13 UTC, minkyu97 commented
수고하셨습니다~
이제 develop 브랜치랑 rebase 또는 머지해서 최신화 해주시고
얼마전 추가된 지원 취소 api에 포트폴리오도 같이 삭제되도록 변경한 뒤에 머지하면 될 것 같아요!

2023-07-25 15:09 UTC, minkyu97 commented on wacruit/src/apps/portfolio/url/models.py
> +    )
넵 마이그레이션 파일도 수정해야돼요

2023-07-27 17:38 UTC, shp7724 commented
👀

2023-07-29 07:04 UTC, fivessun5 commented
마이그레이션 파일 추가 및 지원 취소시 포폴 삭제도 추가했습니다

2023-07-29 07:37 UTC, minkyu97 approved these changes
수고했어~~

2023-07-29 07:39 UTC, merged