Refactor resumes & add tests & withdraw
wafflestudio/wacruit-server pull request #25
Opened 2023-07-22 18:05 UTC by shp7724

- 원래 withdraw만 하려고 했는데, 수정이 필요한 곳들이 좀 보여서 resumes쪽 전반적으로 수정했습니다.
- API spec 변경
- 함수명 및 변수명 더 명확하게 변경
- withdraw api 추가
- create, update, withdraw API 에 대한 테스트 작성

- 논외지만 ResumeSubmission라는 이름이 좀 이상한듯.. ResumeQuestion ←→ ResumeAnswer이 더 적합한거같음

2023-07-22 18:06 UTC, shp7724 commented on wacruit/src/apps/resume/repositories.py
> +                self.session.execute(update_stmt)
on duplicate key update 를 쓰고싶었지만 user_id 가 nullable인 관계로...

2023-07-23 05:45 UTC, minkyu97 commented on wacruit/src/apps/resume/repositories.py
> +                self.session.execute(update_stmt)
ㅇㅎ.. `on_conflict_do_update` 이것도 안 되나요?

2023-07-23 05:49 UTC, shp7724 commented on wacruit/src/apps/resume/repositories.py
> +                self.session.execute(update_stmt)
그거 데이터베이스 종류마다 다른 거 아닌가요
더 깊게 알아보기 귀찮아서 그냥 이렇게 했습니다 ㅠ_

2023-07-23 06:14 UTC, minkyu97 requested changes
고생하셨습니다 (_ _)
근데 withdraw에 포트폴리오 삭제도 들어가야해서 태양이 PR 머지되고 나서 머지해야할 거 같아요.

2023-07-23 06:14 UTC, minkyu97 commented on wacruit/src/apps/resume/views.py
>      current_user: CurrentUser,
근데 `update_resume` 에서 `create_or_update` 해주면 이 api는 안 쓰이지 않을까요??
아니면 클라에서 어떤 걸 써야할지 구분할 방법이 있나요

2023-07-23 06:14 UTC, minkyu97 commented on wacruit/src/apps/resume/views.py
> +@v1_router.delete("/{recruiting_id}/resumes/withdraw", status_code=204)
responses에 `UserNotFoundException` 추가해야할듯요
그리고 `DELETE` 메서드랑 `/withdraw` 로 끝나는 uri가 뭔가 겹치는 것 같은데... `POST` 로 바꾸거나 `/witdraw`를 빼는 게 자연스러운 것 같아요 (`delete_resume` 가 없으니 전 후자가 좋아보이긴 합니다.)

2023-07-23 06:14 UTC, minkyu97 commented on wacruit/src/apps/resume/services.py
> +        )
이거 근데 태양이 PR 머지되면 portfolio 파일 삭제하는 것도 추가해야할듯요 (물론 delete_object 함수 그냥 가져다 쓰면 될듯)

2023-07-23 06:14 UTC, minkyu97 commented on wacruit/src/apps/resume/services.py
> +        user_service: Annotated[UserService, Depends()],
`service` <-> `service` 끼리 연결되는 것보다 `withdraw` api에 `user_service` 를 추가하는 게 어떨까요?

2023-07-23 06:25 UTC, shp7724 commented on wacruit/src/apps/resume/views.py
>      current_user: CurrentUser,
사실 맞아요 ㅋㅋ
create 필요 없을듯해요

2023-07-23 06:26 UTC, shp7724 commented on wacruit/src/apps/resume/services.py
> +        user_service: Annotated[UserService, Depends()],
일반적으로 같은 layer에 있는것끼리는 사용할 수 있지 않나요

2023-07-23 06:27 UTC, shp7724 commented on wacruit/src/apps/resume/repositories.py
> +                .where(ResumeSubmission.recruiting_id == recruiting_id)
그렇게 될 것 같아요

2023-07-23 06:30 UTC, minkyu97 commented on wacruit/src/apps/resume/views.py
>      current_user: CurrentUser,
ㅋㅋㅋ 그렇군요 근데 뭐 있어도 상관없으니 냅두든 삭제하든 편하신대로 하시면 될 듯 합니다.

2023-07-23 06:35 UTC, minkyu97 commented on wacruit/src/apps/resume/services.py
> +        user_service: Annotated[UserService, Depends()],
https://softwareengineering.stackexchange.com/questions/388927/is-it-problematic-to-have-a-dependency-between-objects-of-the-same-layer-in-a-la
오.. 그러네요 제가 잘못 생각했습니다.

2023-07-23 14:13 UTC, fivessun5 commented on wacruit/src/apps/resume/schemas.py
ResumeQuestionDto 이거 안쓰는것 같던데 지워주실수 있나요

2023-07-24 14:25 UTC, shp7724 commented on wacruit/src/apps/resume/schemas.py
이거 필요하긴 해서
그냥 여기서 API 추가해놓을게요

2023-07-24 14:39 UTC, shp7724 commented on wacruit/src/apps/resume/schemas.py
https://github.com/wafflestudio/wacruit-server/pull/25/commits/f800f51203162935226b7d60ebf7614b1e9a185e

2023-07-24 14:39 UTC, shp7724 commented on wacruit/src/apps/resume/schemas.py
@minkyu97 DB 스키마 변경 있어염

2023-07-24 16:24 UTC, minkyu97 approved these changes
포트폴리오 제거 로직은 태양이 PR에서 처리합시다요
수고하셨음다

2023-07-24 16:49 UTC, merged