Judge API 및 SSE를 활용한 코드 제출 API 구현
wafflestudio/wacruit-server pull request #4
Opened 2023-07-05 19:55 UTC by minkyu97

테스트 방법
* wacruit judge 를 docker copose 로 띄운다.
* `.env.local` 에 데이터베이스 정보와 `JUDGE_URL=http://localhost:2358` 를 추가한다.
* `uvicorn wacruit.src.main:app` 으로 wacruit-server 를 실행한다.
* `POST /v1/problem/submission` 에 problem_id, language, source_code 를 바디로, waffle-user-id 를 헤더로 담아서 보낸다.

2023-07-07 02:34 UTC, shp7724 reviewed
수고하셨슴다 ~ 리뷰 남길게요

2023-07-07 02:34 UTC, shp7724 commented on wacruit/src/apps/problem/repositories.py
> +            params={"fields": ",".join(fields)},
`params` 인자가 있는데 url에 `base64_encoded=false`가 있는게 조금 이상한거같아요
base64_encoded도 params 로 관리하면 어떨까요

2023-07-07 02:34 UTC, shp7724 commented on wacruit/src/apps/problem/repositories.py
> +    async def list_submission(self, fields: list[str]) -> GetSubmissionResponse:
judge api 문서에 param 목록이 있는걸로 아는데
`list[str]`말고 pydantic model로 type safe하게 관리하는건 어떨까요

이런식으루
```python
class JudgeQueryParams(BaseModel):
    base64_encoded: bool = False
    ...  # 그 외 나올 수 있는 params
```

2023-07-07 02:34 UTC, shp7724 commented on wacruit/src/apps/problem/repositories.py
> +            self.session.bulk_save_objects(problems)
이건 내부 동작이 어떻게 될지 확신이 없는데 혹시 테스트해보신건가여
가령 integrity check도 잘 되는지 등등.. 
(애초에 여러 문제를 동시에 생성할 일이 있는지도 궁금)

2023-07-07 02:34 UTC, shp7724 commented on wacruit/src/apps/problem/services.py
> +}
이것도 `Enum`으로 통합할 수 있겠네요!

2023-07-07 02:34 UTC, shp7724 commented on wacruit/src/apps/problem/services.py
> +            ),  # type: ignore
이것은 왜 ignore 일까요?

별개로 이 함수 전체를 enumerate 안에 넣기보단 intermediate variable로 저장해두고 사용하는게 보기 편하지 않을까 하는 생각이 드네요

2023-07-07 02:34 UTC, shp7724 commented on wacruit/src/apps/problem/repositories.py
> +from wacruit.src.api.schemas import GetSubmissionResponse
rebase하면 아마 고쳐질거같긴한데 schema는 각 도메인 폴더에 잘 넣으면 될거같아요

2023-07-07 02:34 UTC, shp7724 commented on wacruit/src/apps/problem/services.py
> +            create_submission_request = CreateSubmissionRequest(
Judge 관련 스키마에는 `Judge` prefix를 붙이는게 어떨까요
`JudgeSubmissionRequest` 이런식..
`CodeSubmitRequest`이랑 너무 헷갈리게 생긴듯해요

2023-07-07 02:34 UTC, shp7724 commented on wacruit/src/apps/problem/services.py
> +                )
근데 백준방식으로 하기로 하지 않았나요?
왜 1테케 1요청으로 된거징
아님 1테케에 여러 sub테케가 포함되어있는..그런 느낌인가요

2023-07-07 02:34 UTC, shp7724 commented on wacruit/src/apps/problem/services.py
> +            result.status.id == 3 and f"{result.time},{result.memory}"  # type: ignore
`status`에 computed property 추가해서 `== 3` 이 어떤 의미인지 명시적으로 나타내면 좋을 것 같아요

2023-07-07 02:34 UTC, shp7724 commented on wacruit/src/apps/problem/services.py
> +                self.logger.debug("Request disconnected")
중간에 연결 끊어지면 `break` 해도 되지 않나요?

2023-07-07 02:34 UTC, shp7724 commented on wacruit/src/apps/problem/views.py
> +    return await problem_service.get_all_problems()
이것은 await을 사용할 필요가 있나요?

2023-07-07 02:34 UTC, shp7724 commented on wacruit/src/apps/problem/views.py
> +    problem_service: Annotated[ProblemService, Depends()],
`problem_service: ProblemService = Depends()` 그냥 이렇게 쓰면 안되나요?

2023-07-07 02:34 UTC, shp7724 commented on wacruit/src/apps/problem/views.py
> +    )
이런건 첨보는데 `EventSourceResponse`가 awaitable 함수 인자로 받아서 알아서 잘 실행한담에 클라한테 적절히 푸시해주는 그런 개념인거죠?

2023-07-07 03:41 UTC, minkyu97 commented on wacruit/src/database/models/problem.py
> +    token: Mapped[str] = mapped_column(String(255), nullable=False)
아예 시험 전형 테이블을 추가해야할지 고민입니다! year, 전형 정보에 대한 것을 컬럼으로 추가할지 따로 테이블로 관리하는 게 맞을지 고민되는데 의견 주세용 (아니면 일요일 회의때 같이 얘기해보죠)

2023-07-07 03:44 UTC, minkyu97 commented on wacruit/src/database/models/problem.py
> +    )
problem을 삭제한다는 건 해당 테스트케이들이 전부 필요 없다고 생각했습니다. 혹시 delete 말고 set null 이나 다른 on_delete 옵션을 줘야한다고 생각하시는 게 있나여?

2023-07-07 03:46 UTC, shp7724 commented on wacruit/src/database/models/problem.py
> +    )
testcase는 없어져도 괜찮을것같은데 submission은 set null로 남겨놔도 괜찮지 않을까 싶어서용

2023-07-07 03:54 UTC, minkyu97 commented on wacruit/src/apps/problem/schemas.py
> +TestCaseState = Literal["RUNNING", "SUCCESS", "FAILED"]
`Enum`으로 관리한다는 게 Python의 `Enum` 타입으로 관리하자는 건가요 아니면 MySQL의 `ENUM`으로 관리하자는 건가요??
참고로 전 둘 다 선호하지 않는데 그 이유는 MySQL의 `ENUM`은 ANSI 표준이 아니어서이고 Python의 `Enum`은 어차피 Literal을 써도 웬만하면 IDE또는 정적 타입 검사에서 확인이 되는데 굳이 써야할 필요성을 못 느꼈습니다...만 저 혼자 쓰는 레포가 아니니 다른 분들이 `Enum`이 보기 좋다면 바꾸는 것도 좋다고 생각합니다 :-)

2023-07-07 04:17 UTC, minkyu97 commented on wacruit/src/apps/problem/services.py
> +}
마찬가지 이유로 Enum 타입의 효용성에 대해서 의문을 가지고 있는데 (추가적인 코드 작성을 해야하는데 비해 어떤 효용이 있는지 잘 모르겠음) Enum을 권장하시는 이유가 있을까요??

2023-07-07 04:17 UTC, minkyu97 commented on wacruit/src/apps/problem/services.py
> +            ),  # type: ignore
이거 ignore를 제거하면 자꾸 에러가나는데 에러가 안 나야될 것 같은데 원인을 못 찾아서 새벽 4시에 딥빡해서 ignore했습니다 ㅠㅠㅠ
다시 한 번 원인을 찾아보고 제거할 수 있으면 제거할게요. 다른 분들도 짐작가시는 거 있으면 말씀해주세요 @fivessun5 @serverrepairman 
후자는 반영해두겠습니다!

2023-07-07 04:17 UTC, minkyu97 commented on wacruit/src/apps/problem/services.py
> +                )
백준 방식도 사실 하나의 거대한 테케 집합을 돌리는 게 아니고요, 각각의 라인이 테스트 케이스라면 이걸 N개로 묶은 테스트 케이스 집합이 있고, 이러한 테스트케이스 집합이 M개 있는 형태로 되어있습니다. 이렇게 했을 때의 장점은 테스트케이스마다의 목적성을 명시해서 그룹화시킬 수 있다는 거예요.
예를 들면, 경로 찾기 문제를 낸다고 할 때 30개의 일반 테스트 케이스, 10개의 경로 못 찾는 예외 테스트 케이스, 20개의 효율성 테스트 케이스 이런식으로 구분지을 수 있습니다. 저희가 이번 리크루팅 때 그렇게 빡세게 테케를 만들지 않을 순 있지만 추후의 유연성과 확장성을 위해서 이렇게 만들어두었고, 만약 1개의 테스트케이스만 존재한다고 가정하고 구현한 것에 비해 overhead가 그렇게 크지 않다고 생각해서 이렇게 구현했어요

2023-07-07 04:17 UTC, minkyu97 commented on wacruit/src/apps/problem/services.py
> +                self.logger.debug("Request disconnected")
엇 실수,, 이건 break 넣는 게 맞아요 ㅋㅋㅋ 감사합니다

2023-07-07 04:17 UTC, minkyu97 commented on wacruit/src/apps/problem/services.py
> +            result.status.id == 3 and f"{result.time},{result.memory}"  # type: ignore
computed property가 먼 말인가 했더니 swift에서 사용되는 용어인 것 같군요!
대충 어떤 의미인지는 이해했고 납득도 했습니다. 다음 커밋에서 반영할게요!

2023-07-07 04:17 UTC, minkyu97 commented on wacruit/src/apps/problem/views.py
> +    problem_service: Annotated[ProblemService, Depends()],
안 그래도 중간 회의 때 언급하려고 했는데요, [FastAPI 공식문서](https://fastapi.tiangolo.com/python-types/#type-hints-with-metadata-annotations)에 따르면 이 방법이 파이썬 표준이라고 합니다. 다른 분들도  default_paramter에 Depends()를 넣어야할 불가피한 이유가 없다면 이 방식으로 통일하는 게 어떨까 싶은데 다들 어떻게 생각하시나요?
cc. @fivessun5 @serverrepairman 
참고로 이렇게 했을 때의 대표적인 장점은 다른 코드에서 해당 함수를 직접 호출할 일이 있을 때 의존성 주입이 되지 않아 에러가 발생하는 것을 막을 수 있다는 것이고요, 혹은 해당 매개변수가 DI 대상인지 확인해야할 때 inspect 모듈의 도움이 필요 없다는 것도 있습니다.

2023-07-07 04:17 UTC, minkyu97 commented on wacruit/src/apps/problem/views.py
> +    return await problem_service.get_all_problems()
모든 async 함수는 await을 통해서 받아야 합니다. 그런데 이 경우에는 해당 함수를 async로 정의할 필요가 있는지 의문이긴 하네요.. 요 부분은 다시 한 번 확인해볼게요

2023-07-07 04:17 UTC, minkyu97 commented on wacruit/src/apps/problem/views.py
> +    )
넵넵 맞아요 awaitable한 값을 인자로 받아서 SSE Response를 반환해주는 역할입니다.

2023-07-07 04:25 UTC, minkyu97 commented on wacruit/src/apps/problem/repositories.py
> +            self.session.bulk_save_objects(problems)
안 쓰는 함수라 그냥 삭제해두겠습니다!
그때 그때 필요한 함수들을 작성하는 게 아니라 데이터 레이어부터 차곡차곡 쌓아올리는 방식으로 개발했더니 필요없는 코드가 들어가있는 경우가 왕왕 있네요..

2023-07-07 04:25 UTC, minkyu97 commented on wacruit/src/apps/problem/repositories.py
> +            params={"fields": ",".join(fields)},
엇 그러네용 왜 이렇게 했지.. 반영해두겠씁니다!

2023-07-07 04:25 UTC, minkyu97 commented on wacruit/src/apps/problem/repositories.py
> +    async def list_submission(self, fields: list[str]) -> GetSubmissionResponse:
좋은 생각입니다! 다음 커밋에서 반영할게요

2023-07-07 04:25 UTC, minkyu97 commented on wacruit/src/api/connections.py
> +def get_api_client(env_name: str) -> Callable[[], AsyncIterable[AsyncClient]]:
음.. 저도 당장은 다른 api를 쓸 일이 있을지 생각이 안 나네요. 그냥 api 모듈 자체를 없애버릴까요?

2023-07-07 04:25 UTC, minkyu97 commented on wacruit/src/api/connections.py
> +        if base_url := get_key(env_file, env_name + "_URL"):
사실 pydantic settings를 어떻게 써야할지 몰라서 그냥 무지성으로 작성했는데.. 다시 찾아보고 리팩토링해둘게요

2023-07-07 04:25 UTC, minkyu97 commented on wacruit/src/database/models/problem.py
> +    )
problem이 없을 때 submission을 보존해두어야할 케이스가 생각나지 않는데.. 혹시 어떤 케이스를 고려하신 걸까용?

2023-07-07 04:32 UTC, shp7724 commented on wacruit/src/apps/problem/services.py
> +                )
네 그런 sub테케의 경우라면 좋습니다~

2023-07-07 04:38 UTC, shp7724 commented on wacruit/src/apps/problem/views.py
> +    problem_service: Annotated[ProblemService, Depends()],
> 다른 코드에서 해당 함수를 직접 호출할 일이 있을 때 의존성 주입이 되지 않아 에러가 발생하는 것을 막을 수 있다

이건 이해가 잘 안되는데요, `해당 함수`라는건 `list_problem`을 가리키는건가요? 
의존성 주입이 되지 않으면 에러가 발생해야 하는 것 아닌가요

2023-07-07 04:40 UTC, shp7724 commented on wacruit/src/apps/problem/views.py
> +    return await problem_service.get_all_problems()
내부에 suspension point(`await`)가 없으면 async로 정의해도 sync 함수랑 똑같이 작동하긴 할거에요
(파이썬은 모르겠고 swift에서는 그럼..)

2023-07-07 04:41 UTC, shp7724 commented on wacruit/src/database/models/problem.py
> +    )
그냥 soft delete 느낌으로 이미 제출된 submission은 보존해두는게 언젠간 유용할수도 있지 않을까요 ㅋ

2023-07-07 04:42 UTC, shp7724 commented on wacruit/src/apps/problem/services.py
> +            ),  # type: ignore
checkout 하기 귀찮아서(ㅋㅋ) 물어보는건데 type error 메시지가 뭐라고 나오나요?

2023-07-07 04:43 UTC, shp7724 commented on wacruit/src/apps/problem/schemas.py
> +    is_test: bool = Field(False)
오..그런거까지 구현하나요?

2023-07-07 04:52 UTC, shp7724 commented on wacruit/src/apps/problem/schemas.py
> +TestCaseState = Literal["RUNNING", "SUCCESS", "FAILED"]
python `Enum` (또는 `IntEnum`) 말한거였어요. 

나름 설득을 해보자면.. 
- Literal 타입은 일단 str으로 타입캐스팅이 발생하면 타입체크가 불가능
- Literal은 IDE 리팩토링 기능 사용 불가 (Rename 등)
- `LANG_MAP`에 대한 type annotation이 귀찮아짐. (`LANG_MAP: dict[Literal["C", "C++", "JAVA", ... "SWIFT"], int]` 이건 좀 그렇잖아요)
- computed property + `match .. case` 조합으로 기능을 유연하게 확장 가능 (ex: `Language.PYTHON.needs_compilation == False`)
- 개인적으로 코드에 plain text 들어가는걸 매우 싫어함

정도 이유가 있습니다 ㅎㅎ

```python
LANG_MAP = {
    "C": 100,
    "C++": 101,
    "JAVA": 102,
    "JAVASCRIPT": 103,
    "PYTHON": 104,
    "RUBY": 105,
    "GO": 106,
    "TYPESCRIPT": 107,
    "KOTLIN": 108,
    "SCALA": 109,
    "SQL": 110,
    "SWIFT": 111,
}

class Language(Enum):
    C = 100
    CPP = 101
    JAVA = 102
    JAVASCRIPT = 103
    PYTHON = 104
    RUBY = 105
    GO = 106
    TYPESCRIPT = 107
    KOTLIN = 108
    SCALA = 109
    SQL = 110
    SWIFT = 111
```

2023-07-07 04:54 UTC, shp7724 commented on wacruit/src/api/connections.py
> +def get_api_client(env_name: str) -> Callable[[], AsyncIterable[AsyncClient]]:
아.. `api` 폴더를 따로 만든거군요? 이제 알았다..
네 그냥 apps 폴더에 통합해도 괜춘할거같슴다

2023-07-07 05:36 UTC, minkyu97 commented on wacruit/src/apps/problem/schemas.py
> +TestCaseState = Literal["RUNNING", "SUCCESS", "FAILED"]
1. 타입캐스팅이 발생했을 때 타입체크가 불가능 << 요거 좀 더 자세히 설명해주실 수 있을까요??
LIteral String 이외에는 사용할 일이 없을 거 같은데 타입 캐스팅이 일어날 일이 무엇이 있는지 궁금합니다.
2. 리팩토링은... 동의합니다.
3. 그렇게 할 필요 없이 이렇게 하면 되긴 합니다. `LANG_MAP: dict[SupprtedLanguage, int]`
4. 그리고 제가 아는 선에서 Enum의 사용이 도움이 되는 케이스는 `Language.RUST` 이런 식으로 존재하지 않는 멤버 변수를 호출할 때 에러가 나는 것을 컴파일 타임에 캐치할 수 있다, 정도로 생각하는데요. 어차피 우리가 직접 `LANG_MAP` 을 호출할 일은 잘 없을 것 같고 api단에서 language 값을 보내면 이를 langugage id값으로 바꿔주는 용도로 사용될 것 같은데요, 예를 들어 현재도
``` python
LANG_MAP[request.language.upper()]
```
뭐 이런 식으로 사용되고 있는데, 그러면 마찬가지로 Enum을 사용한들
``` python
Language(request.language.upper())
```
이런 식으로 사용해야될 것 같은데요, 이렇게 되면 사실 Enum을 사용했을 때의 컴파일 타임 타입 안정성이 과연 효용이 있는 것인가 궁금합니다.

2023-07-07 05:44 UTC, minkyu97 commented on wacruit/src/apps/problem/schemas.py
> +TestCaseState = Literal["RUNNING", "SUCCESS", "FAILED"]
그리고 enum을 사용했을 때의 추가적인 문제가 있는데요, 만약 말씀하신대로 Language Enum을 만들어서 사용한다고 하면요, 해당 Enum을 이용해서 아래와 같이 Request 를 만든다고 가정하겠습니다.
``` python
class CodeSubmitRequest(BaseModel):
    problem_id: int
    language: SupportedLanguage = Field(...)
    ...
```
이때 language에는 실제로 들어올 수 있는 값이 C, CPP, JAVA와 같은 String 값이 아니라 100, 101, 102와 같은 숫자 값이 들어와야만 합니다. 이럴 경우 프론트에서 각 language에 대한 실제 데이터베이스 인덱스 값을 알고 있어야하고, 이렇게 되면 클라이언트 단에서 데이터베이스에 대한 종속성이 생기는 됩니다.

2023-07-07 05:57 UTC, minkyu97 commented on wacruit/src/apps/problem/schemas.py
> +    is_test: bool = Field(False)
요거는 옵셔널이긴 한데 채점 api 자체만 완성되면 크게 어렵지 않으니 구현해보려 합니다 ㅎㅎ..

2023-07-07 05:59 UTC, minkyu97 commented on wacruit/src/apps/problem/views.py
> +    return await problem_service.get_all_problems()
파이썬에서는 await으로 받지 않으면 실제 값을 반환하는 게 아니라 coroutine 객체를 반환하고, 해당 코루틴 객체를 실행해줘야 합니다 ㅠ

2023-07-07 06:09 UTC, shp7724 commented on wacruit/src/apps/problem/schemas.py
> +TestCaseState = Literal["RUNNING", "SUCCESS", "FAILED"]
예시 코드입니다
```python
from enum import Enum
from pydantic import BaseModel, validator


class Language(Enum):
    C = 100
    CPP = 101
    JAVA = 102


class CodeSubmitRequest(BaseModel):
    problem_id: int
    language: Language

    @validator("language", pre=True)
    def language_must_be_supported(cls, v) -> Language:
        if isinstance(v, Language):
            return v
        if not isinstance(v, str):
            raise ValueError("Language must be a string.")
        return Language[v.upper()]


if __name__ == "__main__":
    data = {
        "problem_id": 1,
        "language": "java",
    }
    request = CodeSubmitRequest(**data)
    print(request.language.value)  # prints 102
```

2023-07-07 06:13 UTC, minkyu97 commented on wacruit/src/apps/problem/schemas.py
> +TestCaseState = Literal["RUNNING", "SUCCESS", "FAILED"]
class CodeSubmitRequest(BaseModel):
    problem_id: int
    language: Language = Field(...)
    @validator('language', pre=True)
    def lang_to_enum(cls, lang):
        if isinstnace(lang, int):
            return lang
        if isinstance(lang, str):
            return Language[lang].value
```
이렇게 가능하긴 하군요...
흠... 어렵네요 ㅠ 그럼 요거 중간회의 때 다시 한 번 논의해보시죠

2023-07-07 06:13 UTC, shp7724 commented on wacruit/src/apps/problem/views.py
> +    return await problem_service.get_all_problems()
제 말은 `problem_service.get_all_problems()` 자체를 `async`로 정의하는 의미가 없다는 뜻이었어요
`problem_service.get_all_problems()` 내부 구현에 suspension point가 없기 때문에...

2023-07-07 06:19 UTC, shp7724 commented on wacruit/src/apps/problem/schemas.py
> +TestCaseState = Literal["RUNNING", "SUCCESS", "FAILED"]
고민되는 or 논의해야하는 포인트가 무엇인가요?

2023-07-07 06:27 UTC, minkyu97 commented on wacruit/src/apps/problem/schemas.py
> +TestCaseState = Literal["RUNNING", "SUCCESS", "FAILED"]
이게 방법의 차이이지 뭐가 옳고 그르다고 생각하지 않아서요!... 그냥 다수가 좋아하는 방법으로 ㄱㄱ 할까 했습니다

2023-07-07 06:33 UTC, shp7724 commented on wacruit/src/apps/problem/schemas.py
> +TestCaseState = Literal["RUNNING", "SUCCESS", "FAILED"]
넹. 근데 저는 이 경우 Enum으로 얻을 수 있는 이득이 훨씬 크다고 생각하기 때문에 이 방식을 강력하게 어필하고 싶네여. 🤓

2023-07-07 06:39 UTC, shp7724 commented on wacruit/src/apps/problem/schemas.py
> +    testcases: list[Any] | None = Field(None, max_items=10)
(solution 메서드 시그니처를 제공한다는 측면에서) 백준방식이냐 프로그래머스 방식이냐에 따라 차이가 있을 것 같은데,
이번에는 백준 방식으로 하기로 했으니 그냥 stdin, stdout 조합으로 하면 되지 않을까요?

2023-07-07 15:00 UTC, fivessun5 commented on wacruit/src/apps/problem/schemas.py
> +TestCaseState = Literal["RUNNING", "SUCCESS", "FAILED"]
strenum 이 3.11 부터 쓸수 있는 걸로 아는데 그건 어떨지 잠깐 끼적여 봅니다 ㅎㅎ

2023-07-07 15:22 UTC, fivessun5 reviewed
- wacruit judge 를 docker copose 로 띄운다.
이게 정확히 뭔지 잘 모르겠는데 좀 더 구체적으로 설명해주실수 있나용??

2023-07-08 07:20 UTC, minkyu97 commented on wacruit/src/apps/problem/schemas.py
> +TestCaseState = Literal["RUNNING", "SUCCESS", "FAILED"]
@fivessun5 처음 보는 기능이라 찾아봤는데 enum의 각 원소가 String으로 할당될 때 사용 가능해서 지금처럼 문자열을 숫자로 매칭해야하는 경우에는 사용이 어려울 것 같습니다 😭

2023-07-08 07:21 UTC, shp7724 reviewed
아직 작업중인거같지만 틈새 리뷰...

2023-07-08 07:21 UTC, shp7724 commented on wacruit/src/apps/problem/schemas.py
> +TestCaseState = Literal["RUNNING", "SUCCESS", "FAILED"]
쓴다면 IntEnum이 더 적합할거같은데, 그냥 Enum으로도 문제 없어서 괜찮을거같아용

2023-07-08 08:17 UTC, minkyu97 commented on wacruit/src/apps/user/schemas.py
> -        return UserDetailResponse(
1. [pydantic v2 마이그레이션 가이드](https://docs.pydantic.dev/latest/migration/#:~:text=The%20from_orm%20method%20has%20been%20deprecated%3B%20you%20can%20now%20just%20use%20model_validate%20(equivalent%20to%20parse_obj%20from%20Pydantic%20V1)%20to%20achieve%20something%20similar%2C%20as%20long%20as%20you%27ve%20set%20from_attributes%3DTrue%20in%20the%20model%20config.)에 보면 deprecated 되었다고 나오긴 하는데 문제가 있다거나 해서 없어진 건 아니고 새로운 메서드로 대체된 것 같습니다. 저는 라이브러리에서 제공하는 메서드를 사용하는 게 안정성이 더 높을 거라고 생각하고 말씀하신 경우에만 커스텀 from_orm을 정의해도 충분할 것 같다고 생각해요.
2. 내부에서 serialization이 어떻게 진행되는지 직관적으로 알기 어려움 << 요 부분 더 자세히 설명해주실 수 있나요?? 테스트를 통해 원하는대로 작동하는지 여부만 확인되면 충분할 듯 싶은데 내부 작동 원리를 더 직관적으로 알아야하는 이유가 궁금합니다.

2023-07-08 08:18 UTC, minkyu97 commented on wacruit/src/apps/dummy/repositories.py
현재 어디에도 사용되지 않고 있고 단순 참고용 코드라고 보여 주석처리 해두었습니다. 혹시 쓰이고 있는 곳이 있나요?

2023-07-08 08:20 UTC, minkyu97 commented
> * wacruit judge 를 docker copose 로 띄운다.
>   이게 정확히 뭔지 잘 모르겠는데 좀 더 구체적으로 설명해주실수 있나용??

말 그대로 wacruit-judge 레포를 로컬에서 받은 후에 README에 적혀있는대로 docker-compose로 띄워야지만 본 브랜치를 정상적으로 테스트하실 수 있어요

2023-07-08 08:23 UTC, minkyu97 commented on wacruit/src/database/migrations/env.py
> +        logger.info("%s app doesn't have any models", app)
요건 장고에서 사용하는 방식을 따온 건데요, 어차피 app이 몇개 되지 않으니까 어떤 방법을 사용하든 큰 상관 없지만 waffledotcom-server 에서도 가져가볼까 생각하고 있었습니다. hacky 하다는 게 좀 잘 와닿지 않는데 이 방법이 문제되리라 생각하는 건 구체적으로 어떤 이유 때문일까요??

2023-07-08 08:28 UTC, minkyu97 commented on wacruit/src/apps/problem/schemas.py
> +TestCaseState = Literal["RUNNING", "SUCCESS", "FAILED"]
IntEnum이 단순히 이름만 IntEnum이고 Enum을 상속 받고 오버라이딩된 게 없더라고요?? 그래서 그냥 Enum을 사용했는데 혹시 제가 잘못 알고 있는 거면 지적 부탁드려요~

2023-07-08 08:46 UTC, fivessun5 commented
아 wacruit judge repo의 존재를 몰랏어요. 그러면 리드미에 해당 레포 링크를 걸어둬도 좋을것 같아요!!

2023-07-08 10:16 UTC, shp7724 commented on wacruit/src/apps/problem/schemas.py
> +TestCaseState = Literal["RUNNING", "SUCCESS", "FAILED"]
IntEnum 쓰면 `Language.C == 100` 이런식으로 직접 비교가 가능할걸요?
저도 문서 잠깐 본게 다라서..

2023-07-08 10:21 UTC, shp7724 commented on wacruit/src/apps/user/schemas.py
> -        return UserDetailResponse(
orm 객체를 custom dto로 변환하는 경우 고려할게 좀 있을텐데 (lazy fetching이라든지)
모든 걸 라이브러리에 맡길 수 있을지 의구심이 들어서요. pydantic은 validation 라이브러리지 orm 라이브러리가 아닌지라..
그래도 테스트해서 문제 없으면 이대로 사용하는것도 큰 이견은 없습니다

2023-07-08 10:23 UTC, minkyu97 commented on wacruit/src/apps/problem/schemas.py
> +TestCaseState = Literal["RUNNING", "SUCCESS", "FAILED"]
흠... 그냥 Enum으로 가겠습니다

2023-07-08 10:23 UTC, shp7724 commented on wacruit/src/apps/dummy/repositories.py
아 dummy router가 사라졌나보네요?
네 뭐 이제는 지워도 무방할듯합니다

2023-07-08 10:31 UTC, shp7724 commented on wacruit/src/database/migrations/env.py
> +        logger.info("%s app doesn't have any models", app)
`globals()` 가 좀 걸려서요..
global namespace를 이렇게 동적으로 override하면 naming conflict 발생하거나 했을 때 버그 추적하기도 어렵고.. 영향범위를 직관적으로 파악하기가 어려워져서 antipattern 처럼 느껴지는 것 같아요

2023-07-08 10:44 UTC, minkyu97 commented on wacruit/src/apps/dummy/repositories.py
dummy router 는 지금도 사용되고 있습니다! 현재 develop 브랜치에도 해당 레포지터리를 사용하지 않고 있어요

2023-07-08 10:47 UTC, shp7724 commented on wacruit/src/apps/dummy/repositories.py
아하 이해했슴다

2023-07-08 10:52 UTC, minkyu97 commented on wacruit/src/database/migrations/env.py
> +        logger.info("%s app doesn't have any models", app)
많이들 헷갈리는 부분일 수 있는데, globals()는 앱 전체의 전역변수가 아니라 해당 모듈 내의 전역변수입니다. ([공식문서 참조](https://docs.python.org/ko/3.6/library/functions.html#globals))
그리고 기존에는 아래와 같이 작성되어 있었는데요,
``` python
from <module_name> import *
```
사실 위 코드가 하는 일은 사실 제가 작성한 것과 동일하게 해당 모듈의 globals를 현재 모듈의 globals에 업데이트하는 것과 같습니다.
즉 naming conflict 등 버그를 추적하기 위함이라면 아예 이렇게 아래와 같이 import 대상도 명시적으로 해주는 게 맞습니다.
``` python
from <module_name> import <some_class_or_method>
```
그리고, 사실 이 `env.py` 파일은 오직 alembic에서만 쓰이고 fast api 앱 어디에서도 참조되지 않습니다! db 마이그레이션할 일이 많지 않기 때문에 크게 문제되지 않을 거 같아요. 애초에 마이그레이션 자체가 alembic 에게 전부 맡겨놓고 무지성으로 하는 게 아니라 마이그레이션 하기 전 생성된 마이그레이션 파일을 검수하는 일도 응당 필요하니까요

2023-07-08 11:08 UTC, shp7724 commented on wacruit/src/database/migrations/env.py
> +        logger.info("%s app doesn't have any models", app)
흐음.. 해당 모듈이라면 그래도 결국 해당 파일 외부에까지 영향을 미치는건 아닌건가요?

그러고보니 애초에 여기서 globals().update가 필요한 이유가 뭔가여? 이거 없으면 마이그레이션 잘 안되나요?

2023-07-08 11:47 UTC, minkyu97 commented on wacruit/src/database/migrations/env.py
> +        logger.info("%s app doesn't have any models", app)
음.. 전 해당 모델들을 import 하면 마이그레이션에 포함되고 안 하면 포함이 안 되길래 당연히 globals 변수에서 찾을 줄 알았는데 [공식문서](https://alembic.sqlalchemy.org/en/latest/autogenerate.html#controlling-what-to-be-autogenerated) 찾아보니 그게 아니라 모듈을 import 할 때 해당 테이블들의 클래스가 생성되는 시점에 마이그레이션 대상에 포함되는 건가 보네요.
`DeclarativeBase` 클래스의 정의를 찾아보니 `DeclarativeAttributeIntercept` << 이 메타클래스에서 그런 일을 해주나봐요...
혼동 드려서 미안요 globals() 업데이트하는 부분은 다음 커밋에서 지우도록 하겠습니다 ㅠ

2023-07-10 18:41 UTC, minkyu97 commented
pytest도 프리커밋에 넣어두면 좋겠군요
아직 리팩토링할 부분이 많은데 일단 머지하고 PR을 나눠서 올리는 게 더 좋을 것 같습니다.
코멘트들 대부분 반영했는데 최종적으로 한 번 슥 봐주세요~ 문제 없는 것 같으면 화요일 중으로 머지하겠습니다.
@wafflestudio/waffledotcom-backend

2023-07-11 00:20 UTC, shp7724 commented on wacruit/src/apps/judge/config.py
> +class APIConfig(BaseSettings):
@minkyu97 이거 반영 안된듯합니다

2023-07-11 00:20 UTC, shp7724 commented on wacruit/src/apps/judge/config.py
> +    URL: str = ""
@minkyu97 이것두

2023-07-11 00:21 UTC, shp7724 commented on wacruit/src/apps/problem/repositories.py
> +    async def list_submission(self, fields: list[str]) -> GetSubmissionResponse:
@minkyu97 이것두

2023-07-11 00:22 UTC, shp7724 commented on wacruit/src/apps/problem/services.py
> +            result.status.id == 3 and f"{result.time},{result.memory}"  # type: ignore
@minkyu97 아마 이것도..? 모바일이라 혹시 반영된거면 무시해주세요

2023-07-11 00:23 UTC, shp7724 commented on wacruit/src/apps/problem/services.py
> +                self.logger.debug("Request disconnected")
@minkyu97 아마 이것도..

2023-07-11 00:23 UTC, shp7724 commented
@minkyu97 몇개 반영 안된게 있어서 멘션했어요~ 그것만 되면 머지해도 될듯 합니다

2023-07-11 00:36 UTC, shp7724 commented on wacruit/src/apps/common/enums.py
> +    JAVASCRIPT = 103
원래 있던 LANG_MAP은 지워도 될거같아여

2023-07-11 01:38 UTC, minkyu97 commented on wacruit/src/apps/problem/services.py
> +            result.status.id == 3 and f"{result.time},{result.memory}"  # type: ignore
해당부분 Enum으로 변경했는데 여전히 숫자랑 비교하고 있었네요 ㄷㄷ
반영했습니다

2023-07-11 01:42 UTC, minkyu97 commented on wacruit/src/apps/problem/services.py
> +                self.logger.debug("Request disconnected")
감사함다!
0198d81

2023-07-11 01:44 UTC, minkyu97 commented on wacruit/src/apps/problem/views.py
> +    return await problem_service.get_all_problems()
65a6da2

2023-07-11 01:46 UTC, minkyu97 commented on wacruit/src/apps/judge/config.py
> +    URL: str = ""
5725a7e

2023-07-11 01:46 UTC, minkyu97 commented on wacruit/src/apps/judge/config.py
> +class APIConfig(BaseSettings):
5725a7e

2023-07-11 01:48 UTC, minkyu97 commented on wacruit/src/apps/common/enums.py
> +    JAVASCRIPT = 103
요건 1014198ddc23a6ce6ae5017d44fe75429af347af 에서 같이 반영되었습니다!

2023-07-11 01:48 UTC, minkyu97 commented
@shp7724 빠진 게 좀 많았네... 거진 다 반영했습니다 체크 감사감사

2023-07-11 04:12 UTC, shp7724 requested changes

2023-07-11 04:12 UTC, shp7724 commented on wacruit/src/apps/problem/services.py
> +        while len(running_testcases_set) > 0 and await request.is_disconnected():
이거 조건에 not이 들어가야할거같은데 체크좀요~
글구 `if await ~ : break`가 좀더 가독성이 좋은 느낌 ㅋㅋ

2023-07-11 04:12 UTC, shp7724 commented on wacruit/src/apps/judge/repositories.py
> +        res.raise_for_status()
https://github.com/wafflestudio/wacruit-server/pull/4#discussion_r1255132030

이것두

2023-07-11 04:16 UTC, minkyu97 commented on wacruit/src/apps/problem/services.py
> +        while len(running_testcases_set) > 0 and await request.is_disconnected():
3e0e826

2023-07-11 04:16 UTC, minkyu97 commented on wacruit/src/apps/judge/repositories.py
> +        res.raise_for_status()
이건 다시 생각해보니까 그냥 바꿀 필요가 있나 싶다 어차피 거의 안 바뀔 것 같은뎅

2023-07-11 04:18 UTC, minkyu97 commented on wacruit/src/apps/judge/repositories.py
> +        res.raise_for_status()
그리고 저게 스키마가
``` json
{
  "base64_encoded": bool,
  "fields": comma-separated-fields,
  ...
}
```
일케 되기도 하고 fields는 바뀔 일이 잘 없을 것 같음

2023-07-11 04:19 UTC, shp7724 commented on wacruit/src/apps/judge/repositories.py
> +        res.raise_for_status()
그래? 더 추가 안되면 걍 둬도 상관 없긴 해
난 요청마다 제한시간같은거 커스텀할 일 있을까봐..ㅎ

2023-07-11 04:20 UTC, shp7724 approved these changes
수고하셧슴다

2023-07-11 04:21 UTC, minkyu97 commented on wacruit/src/apps/judge/repositories.py
> +        res.raise_for_status()
흠.. 일리있는 말이긴 한데 이거 슬슬 PR이 너무 커지는 것 같아서 그랬징
다른 급한 api 먼저 파고 내가 리팩토링 PR 파서 전체적으로 손 좀 볼게 🥲

2023-07-11 04:22 UTC, minkyu97 commented
@shp7724 🧇 🧇 🧇 🧇 🧇  x 100
코드 리뷰에 시간 많이 써줘서 넘 고생 많으셨고 넘 고마우이...
내가 봐도 고쳐야 될 부분이 많긴 한데 다른 급한 거 먼저 하고 빠른 시일 내에 리팩토링 하겠슴다 ㅠㅠ

2023-07-11 04:34 UTC, merged