feat: Portfolio V2 API
wafflestudio/wacruit-server pull request #61
Opened 2023-11-05 11:39 UTC by fivessun5

2023-11-06 14:41 UTC, minkyu97 requested changes
수고 많았어~~ 리뷰 한 번 읽어봐줘

2023-11-06 14:41 UTC, minkyu97 commented on pyproject.toml
> +moto = {version = "4.2.7", extras = ["all", "ec2", "s3"]}
👍

2023-11-06 14:41 UTC, minkyu97 commented on wacruit/src/apps/portfolio/file/aws/s3/utils.py
> +        # assert None, (s3_bucket, s3_object)
P2: 이건 지워도 되는 거죠?

2023-11-06 14:41 UTC, minkyu97 commented on wacruit/src/apps/portfolio/file/models.py
> +    term: Mapped[str255] = mapped_column(nullable=False)
P1: 이거 term이 기수? 회차?를 의미하는 건가요?
`recruiting.models.Recruiting.id` 랑 연결하는 게 어떨까요?

2023-11-06 14:41 UTC, minkyu97 commented on wacruit/src/apps/portfolio/file/services_v2.py
> +    def get_presigned_url_for_post_portfolio(
P1: 흠.. 여기서요, `PortfolioFile`에 미리 행을 추가해놓고 해당 테이블에 완료 여부 flag 필드를 하나 추가하는 건 어떨까요?
그래서 get할 때는 업로드가 완료된 애들만 보여주거나, 아니면 다 보여주되 완료 여부를 프론트에 함께 던져서 업로드 중임을 표시할 수도 있고요.
그리고 이 플래그를 이용해서 cron job 등으로 일정 주기마다 배치 돌면서 제대로 업로드 안 된 파일들 정리하거나 아니면 그냥 이 행이 만들어질 때 fastapi background job으로 하루 뒤 완료 안 된 거 확인하고 삭제 이런 로직 추가할 수도 있을 것 같은데 한 번 검토해주세용

2023-11-06 14:41 UTC, minkyu97 commented on wacruit/src/apps/portfolio/file/services_v2.py
> +        ]
P2: 안 쓰는 거죠?

2023-11-06 14:41 UTC, minkyu97 commented on wacruit/src/apps/portfolio/file/views_v2.py
> +from wacruit.src.apps.portfolio.file.schemas import PortfolioNameResponse
P2: 요것도 안 쓰는 것 같네요

2023-11-06 14:41 UTC, minkyu97 commented on wacruit/src/apps/portfolio/file/services_v2.py
> +            delete_object(self._s3_client.client, self._s3_config.bucket_name, obj)
P3: 어차피 같은 코드긴 하지만 resume.services 에서 쓰는 거를 v1에서 v2로 바꿔주는 게 좋겠습니다.

2023-11-06 14:41 UTC, minkyu97 commented on wacruit/src/apps/portfolio/file/repositories.py
> +    def get_all_applicant_user_ids(self) -> Sequence[intpk]:
P2: 이것도 안 쓰는 것 같네요.. 만약 쓰게 된다면 term(또는 recruiting.id) 를 인자로 받아야할 것 같아요

2023-11-09 12:24 UTC, shp7724 commented on wacruit/src/apps/portfolio/file/models.py
> +    term: Mapped[str255] = mapped_column(nullable=False)
참고로 기수는 `generation`으로 https://github.com/wafflestudio/waffledotcom-server/pull/20/files 여기서 추가했어요
구글링과 chatgpt에 검색해봤는데 generation이 가장 근접한거같더라고요

2023-11-09 12:24 UTC, shp7724 commented on wacruit/src/tests/portfolio/file/test_portfolio_file_service.py
> +    )
`test1.pdf`를 create 해주는 코드가 어디 있나요? conftest에 있을 줄 알았는데 안보이네요

2023-11-26 05:47 UTC, fivessun5 commented on wacruit/src/apps/portfolio/url/services.py
> +        if term is not None:
그건 프론트의 v1 사용처가 다 제거되고 나서 하는게 더 좋을것 같아요

2023-11-26 05:48 UTC, fivessun5 commented on wacruit/src/tests/portfolio/file/test_portfolio_file_service.py
> +    )
presigned url 을 생성하는 함수라서, 실제 해당 파일자체는 없어도 되서 따로 안만들었어요 ㅋㅋ

2023-11-26 05:48 UTC, fivessun5 commented on wacruit/src/apps/portfolio/file/repositories.py
> +    def get_all_applicant_user_ids(self) -> Sequence[intpk]:
제거하겠습니다

2023-11-26 05:48 UTC, fivessun5 commented on wacruit/src/apps/portfolio/file/services_v2.py
> +            delete_object(self._s3_client.client, self._s3_config.bucket_name, obj)
넵

2023-11-26 05:48 UTC, fivessun5 commented on wacruit/src/apps/portfolio/file/views_v2.py
> +from wacruit.src.apps.portfolio.file.schemas import PortfolioNameResponse
제거했습니다

2023-11-26 05:48 UTC, fivessun5 commented on wacruit/src/apps/portfolio/file/services_v2.py
> +        ]
제거할게용

2023-11-26 05:48 UTC, fivessun5 commented on wacruit/src/apps/portfolio/file/services_v2.py
> +    def get_presigned_url_for_post_portfolio(
cron job 까지 구현한다면 이상적으로는 좋은것 같아요. 그런데  해당 작업까지 진행하기는 어려울것 같아요. 
후처리 로직없는 구조면 upload 가 되지 않고 presigned url 을 생성할때마다 row 가 추가될텐데, 생각해보면 사용자가 많을것 같지는 않아서 괜찮을 듯하니 일단 그 구조로 해두겠습니다.

2023-11-26 05:48 UTC, fivessun5 commented on wacruit/src/apps/portfolio/file/aws/s3/utils.py
> +        # assert None, (s3_bucket, s3_object)
넵

2023-11-26 05:49 UTC, fivessun5 commented on wacruit/src/apps/portfolio/file/models.py
> +    term: Mapped[str255] = mapped_column(nullable=False)
generation = mapped_column(Foreignkey("recruiting.id")) 로 바꿔둘게요

2023-11-26 06:11 UTC, minkyu97 commented on wacruit/src/apps/portfolio/file/services_v2.py
> +    def get_presigned_url_for_post_portfolio(
cron job은.. 신홍이가 만들어준 슬랙 동기화 api와 함께 묶어서 제가 개발하겠슴다

2023-11-26 12:47 UTC, fivessun5 commented
portfolio_url table 의 generation column 에 null 값을 주고 싶지 않은데 이거 마이그레이션 방법이 좋은게 있을까요? @wafflestudio/waffledotcom-backend

2023-12-10 13:26 UTC, minkyu97 commented on wacruit/src/database/migrations/versions/2023_11_05_1719-2603f3af2e99_portfolio_v2.py
> +    )
@fivessun5 하도 정신이 없어서 피드백이 늦었네요 ㅠ
이거 nullable한 게 문제인 거죠??
그냥 그럼 nullable=False로 해두고, 어차피 저희 마이그레이션할 때 sql로 뽑아서 직접 날려야하니까 그때 조금 수정합시다.
히스토리를 위해서 이 부분에 주석만 추가해주세요
이거 말고는 이제 머지해도 되는 거죠??

2023-12-10 13:54 UTC, minkyu97 commented on wacruit/src/database/migrations/versions/2023_11_05_1719-2603f3af2e99_portfolio_v2.py
> +    )
저도 스웨거로 테스트해보니까 큰 문제 없는 거 같긴하네요
근데 generation << 이거 컬럼명이 좀 모호한 거 같은데 그냥 recruiting_id 로 하는 게 더 명확하지 않을까요??
recruiting_id가 generation이랑 1:1 대응일 순 있지만 같은 값은 아니라서..

2023-12-17 10:06 UTC, fivessun5 commented on wacruit/src/database/migrations/versions/2023_11_05_1719-2603f3af2e99_portfolio_v2.py
> +    )
recruiting_id 로 수정해두었어요..!
null 은 일단 True 로 해두고, 디비 조작후 변경 해볼겠습니다

2023-12-21 12:12 UTC, minkyu97 approved these changes

2023-12-21 12:12 UTC, minkyu97 commented on wacruit/src/apps/portfolio/file/models.py
> -    generation: Mapped[int] = mapped_column(
👍

2023-12-29 08:30 UTC, merged