Resume 모델 정의
wafflestudio/wacruit-server pull request #7
Opened 2023-07-13 14:46 UTC by serverrepairman

아직 test 및 에러 처리 부분은 제대로 만들지 못했지만, 모델 공유 등을 위해 최대한 빨리 올리는 편이 좋을 것 같아서 먼저 PR 올립니다.
problems 모듈을 마이그레이션 할 때 오류가 생겨서 ondelete를 CASCADE로 바꿔놓긴 했는데 이부분은 논의가 필요할 거 같습니다

2023-07-13 15:12 UTC, minkyu97 commented
헉 커밋이 단 하나... 😱

2023-07-14 05:39 UTC, minkyu97 requested changes
회사라서 짬짬히 리뷰해봤는데 퇴근하고 다시 한 번 자세히 볼게요~

2023-07-14 05:39 UTC, minkyu97 commented on wacruit/src/apps/resume/views.py
> +async def list_resumes(
await을 사용하지 않는 path operation들의 async 키워드는 (특별한 이유가 없다면) 전부 제거해주세요! async 함수 내에서 mysql 쿼리 등 blocking I/O가 발생하는 경우 메인 이벤트 루프를 블록하는 원인이 됩니다.
https://fastapi.tiangolo.com/async/#path-operation-functions

2023-07-14 05:39 UTC, minkyu97 commented on wacruit/src/apps/resume/views.py
> +async def list_resumes(
그리고 `get_resume` 이 따로 있어야 할 것 같아요
`get_resume` 는 해당 user의 지원서만 반환하고,
`list_resumes` 는 admin만 사용가능하도록 `is_admin` 을 조건으로 달아주시면 좋겠습니다.

2023-07-14 05:39 UTC, minkyu97 commented on wacruit/src/apps/resume/views.py
> +) -> list[ResumeSubmissionWithUserDto]:
그리고 각 operation들에서 `user_id` 를 request 로 받고 계신데 얘네 모두 `get_current_user` 를 사용하는 방향으로 변경해주세요

2023-07-14 05:39 UTC, minkyu97 commented on wacruit/src/apps/resume/views.py
> +) -> ListResponse[ResumeSubmissionWithUserDto]:
그리고 사소하지만, 여기서만 `list` 대신 `ListResponse` 를 사용한 이유가 있을까요?

2023-07-14 05:39 UTC, minkyu97 commented on wacruit/src/apps/resume/views.py
> +    request: Sequence[ResumeSubmissionCreateDto],
마찬가지로 `Sequence` 를 자주 사용하셨던데, `list` 대신 `Sequence` 를 사용한 이유가 있을까요??

2023-07-14 05:39 UTC, minkyu97 commented on wacruit/src/apps/resume/services.py
> +                raise ResumeNotFound
`get_resume_by_id` 에서 아래와 같이 반환하고 있는데요
```python
        return self.session.execute(query).scalar_one()
```
`scalar_one` 함수는 애초에 반환하는 값이 없을 경우 에러를 발생시킵니다. ([출처](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Result.scalar_one))
따라서 repository 쪽에 try catch 로 에러를 핸들링하는 것이 좋아보입니다. (`scalar_one` 대신 `scalar` 나 `first` 등을 사용하는 방법도 있지만, 제 생각에는 repository 쪽에서 에러를 발생시키는 게 더 적절해 보여요.)

2023-07-15 07:00 UTC, shp7724 commented on wacruit/src/apps/resume/views.py
> +) -> ListResponse[ResumeSubmissionWithUserDto]:
이거 제가 만든건데요. json response에서 plain list보다는 dict 형태로 내려주는게 확장성 측면에서 더 유리하다고 생각해서 아래와 같이 구현해두었습니다.

```python
T = TypeVar("T")
class ListResponse(GenericModel, Generic[T]):
    items: list[T]
class PaginatedResponse(GenericModel, Generic[T]):
    items: list[T]
    next_cursor: int | None = None

```

2023-07-15 07:06 UTC, shp7724 reviewed
슥 봤는데 전반적으로 기존 컨벤션과 align이 잘 되어있어서 민규형이 언급한 부분 이외에는 괜찮은거같아요~
테스트만 빠르게 작성 부탁드려요

2023-07-15 17:27 UTC, minkyu97 commented on wacruit/src/apps/resume/views.py
> +    request: Sequence[ResumeSubmissionCreateDto],
아하 sqlalchemy 2.0 버전의 orm을 사용하려면 Sequence를 사용해야 제대로 타입체킹이 되는군요
작성하신대로 하는 게 좋아보입니다.

2023-07-15 18:48 UTC, minkyu97 commented on wacruit/src/apps/resume/repositories.py
> +            .where(ResumeSubmission.recruiting_id == recruiting_id)
[공식 문서](https://docs.sqlalchemy.org/en/14/orm/loading_relationships.html)도 찾아보고 직접 raw 쿼리 로깅도 해봤는데, 여기서 이렇게 join 해봤자 실제로는 처음 쿼리 실행할 때 의미없는 join이 실행되고, 나중에 user를 가져올 때 다시 한 번 select 문이 수행되는 것 같습니다. 
아래와 같이 바꾸는 게 적절할 듯 싶습니다.
```suggestion
from sqlalchemy.orm import joinedload
...
            select(ResumeSubmission)
            .options(joinedload(ResumeSubmission.user))
            .where(ResumeSubmission.recruiting_id == recruiting_id)
```

2023-07-16 13:27 UTC, serverrepairman commented on wacruit/src/tests/conftest.py
>          DeclarativeBase.metadata.create_all(bind=engine)
반영하겠습니다~

2023-07-16 13:27 UTC, serverrepairman commented on wacruit/src/apps/resume/models.py
> +        "Recruiting", back_populates="resume_questions"
앗 그렇군요..!

2023-07-16 13:27 UTC, serverrepairman commented on wacruit/src/apps/resume/models.py
> +class ResumeSubmission(DeclarativeBase):
추가하겠습니다

2023-07-16 16:35 UTC, serverrepairman commented on wacruit/src/apps/resume/repositories.py
> +            .where(ResumeSubmission.recruiting_id == recruiting_id)
일단 내용들 전부 반영하기는 하였으나, 아직 자잘한 오류들이 있어  월요일까지는 반영하겠습니다

2023-07-18 13:44 UTC, minkyu97 approved these changes
수고하셨어요~

2023-07-18 15:18 UTC, merged